"""
可视化模块 - 生成现代化的 HTML 热点看板
"""

import logging
import os
from datetime import datetime
from typing import Dict, List, Optional
from src.models import NewsItem

logger = logging.getLogger(__name__)

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TrendPulse | 智能趋势看板</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=Noto+Sans+SC:wght@400;700&display=swap" rel="stylesheet">
    <style>
        :root {{
            --bg-color: #f5f5f7;
            --card-bg: rgba(255, 255, 255, 0.8);
            --accent-color: #007aff;
        }}
        @media (prefers-color-scheme: dark) {{
            :root {{
                --bg-color: #000000;
                --card-bg: rgba(28, 28, 30, 0.8);
            }}
        }}
        body {{
            font-family: 'Inter', 'Noto Sans SC', sans-serif;
            background-color: var(--bg-color);
            transition: all 0.3s ease;
        }}
        .glass {{
            background: var(--card-bg);
            backdrop-filter: blur(20px);
            -webkit-backdrop-filter: blur(20px);
            border: 1px solid rgba(255, 255, 255, 0.1);
        }}
        .card-hover:hover {{
            transform: translateY(-4px);
            box-shadow: 0 12px 24px rgba(0, 0, 0, 0.1);
        }}
    </style>
</head>
<body class="text-gray-900 dark:text-gray-100 min-h-screen p-4 md:p-8">
    <div class="max-w-5xl mx-auto">
        <!-- Header -->
        <header class="flex justify-between items-end mb-12">
            <div>
                <h1 class="text-4xl font-bold tracking-tight mb-2">TrendPulse</h1>
                <p class="text-gray-500 dark:text-gray-400">智能信息发现与提炼 · {date_str}</p>
            </div>
            <div class="hidden md:block">
                <span class="px-3 py-1 glass rounded-full text-sm font-medium border border-blue-500/30 text-blue-500">
                    Live Updates
                </span>
            </div>
        </header>

        <!-- Daily Insight -->
        {insight_html}

        <!-- Content Grid -->
        <div class="space-y-12">
            {sections_html}
        </div>

        <footer class="mt-20 py-8 border-t border-gray-200 dark:border-gray-800 text-center text-sm text-gray-400">
            Generated by Antigravity AI @ {time_str}
        </footer>
    </div>
</body>
</html>
"""

SECTION_TEMPLATE = """
<section>
    <div class="flex items-center gap-3 mb-6">
        <h2 class="text-2xl font-bold">{label}</h2>
        <span class="px-2 py-0.5 bg-blue-100 dark:bg-blue-900/30 text-blue-600 rounded text-xs font-bold">{count}</span>
    </div>
    
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        {items_html}
    </div>
</section>
"""

ITEM_TEMPLATE = """
<div class="glass p-5 rounded-2xl card-hover transition-all duration-300 flex flex-col justify-between">
    <div>
        <div class="flex justify-between items-start mb-3">
            <span class="text-xs font-bold px-2 py-1 bg-gray-200 dark:bg-gray-800 rounded-md text-gray-500">{platform}</span>
            <span class="text-xs text-blue-500 font-medium">{hot_value}</span>
        </div>
        <h3 class="text-lg font-semibold leading-tight line-clamp-2 mb-2">
            <a href="{url}" target="_blank" class="hover:text-blue-500 transition-colors">{title}</a>
        </h3>
        <p class="text-gray-500 dark:text-gray-400 text-sm line-clamp-3 leading-relaxed">
            {content}
        </p>
    </div>
</div>
"""

INSIGHT_TEMPLATE = """
<div class="glass rounded-3xl p-8 mb-12 border-l-4 border-blue-500 bg-gradient-to-r from-blue-500/5 to-transparent">
    <div class="text-xs font-bold text-blue-500 uppercase tracking-widest mb-2">Today's Insight</div>
    <div class="text-2xl font-medium leading-relaxed italic">
        "{insight_text}"
    </div>
</div>
"""

class DashboardGenerator:
    def __init__(self, output_dir: str = "output"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

    def generate(self, keyword_results: Dict[str, List[NewsItem]], daily_insight: Optional[str] = None):
        date_now = datetime.now()
        date_str = date_now.strftime("%Y年%m月%d日")
        time_str = date_now.strftime("%H:%M:%S")

        insight_html = ""
        if daily_insight:
            insight_html = INSIGHT_TEMPLATE.format(insight_text=daily_insight)

        sections_html_list = []
        for label, items in keyword_results.items():
            if not items:
                continue
                
            items_html_list = []
            for it in items:
                items_html_list.append(ITEM_TEMPLATE.format(
                    platform=it.platform,
                    hot_value=it.hot_value or "",
                    title=it.title,
                    url=it.url,
                    content=it.content or "无详细背景信息。"
                ))
            
            sections_html_list.append(SECTION_TEMPLATE.format(
                label=label,
                count=len(items),
                items_html="".join(items_html_list)
            ))

        final_html = HTML_TEMPLATE.format(
            date_str=date_str,
            time_str=time_str,
            insight_html=insight_html,
            sections_html="".join(sections_html_list)
        )

        output_path = os.path.join(self.output_dir, "dashboard.html")
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(final_html)
        
        logger.info("🎨 看板已生成: %s", output_path)
        return output_path
